# Generated by Django 3.1.5 on 2021-01-12 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 12, 20, 41, 20, 871072)),
        ),
    ]
